name: Java CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # Runnerにgitリポジトリのコピーをダウンロード
      - name: CheckOut
        uses: actions/checkout@v3

      # Java 17をセットアップ
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache : maven

      # maven build
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

      # Test実行
      - name : Test with Maven
        run : mvn --batch-mode test
